# (Meta-)Dynamics of rotor systems

run with dftb_plumed conda environment

In [3]:
from ase.visualize import view
from ase.io import read

atoms = read('../data/structures/new_systems/ktu_002.cif')

# view(atoms)
# len(atoms)

/home/dlb/anaconda3/envs/dftb_plumed/lib/python3.10/site-packages/ase/io/cif.py:401: UserWarning: crystal system 'triclinic' is not interpreted for space group Spacegroup(2, setting=1). This may result in wrong setting!
  warnings.warn(


264

In [6]:
# !ulimit -s unlimited
# conda env export > dftb_plumed.yml
# https://wiki.fysik.dtu.dk/ase/ase/calculators/dftb.html
# https://dftb.org/parameters/download

# export ASE_DFTB_COMMAND="/path/to/dftb+ > PREFIX.out"
# export DFTB_PREFIX=/path/to/mio-0-1/
import os

os.environ['OMP_NUM_THREADS'] = "6,1"
os.environ["ASE_DFTB_COMMAND"] = "ulimit -s unlimited; /home/dlb/anaconda3/envs/dftb_plumed/bin/dftb+ > PREFIX.out"
os.environ["DFTB_PREFIX"] = "/home/dlb/Downloads/pbc-0-3"
# os.environ["DFTB_PREFIX"] = "/home/dlb/Downloads/auorgap-1-1" # doesn't work for now with crystal...

# import os

# os.environ["ASE_DFTB_COMMAND"] = "/home/dlb/anaconda3/envs/qe/bin/dftb+"
# os.environ["DFTB_PREFIX"] = "/home/dlb/Downloads/pbc-0-3"

In [59]:
# %%capture cap

%load_ext autoreload
%autoreload 2


# https://www.plumed.org/doc-v2.7/user-doc/html/_m_e_t_a_d.html
# https://github.com/dftbplus/dftbplus/issues/1064
# try with numpy 1.22　
# https://gitlab.com/Sucerquia/ase-plumed_tutorial

from ase.calculators.lj import LennardJones
# from ase.calculators.plumed import Plumed
from runner.plumed import Plumed
# from plumed import Plumed
from ase.constraints import FixedPlane
from ase.io import read
from ase import units

from ase.geometry.analysis import Analysis
from ase.constraints import FixAtoms, FixBondLengths

# import plumed

from ase.calculators.dftb import Dftb



ps = 1000 * units.fs
timestep = 0.1 # in what units? 

# height 30.50 is fast

setup = [f"UNITS LENGTH=A TIME={1/ps} ENERGY={units.mol/units.kJ}",
        #  "d: DISTANCE ATOMS=1,2 ",
        "at8: FIXEDATOM AT=-0.3652684296711638,5.59639757164289,11.089411052917308",
        "at6: FIXEDATOM AT=-0.5388786945959876,6.471914514609469,10.07028636148657",
        "c1: CENTER ATOMS=at8,at6",
        "c2: CENTER ATOMS=67,69,73,77,79,83",
        "c3: CENTER ATOMS=7,9,11,13,15,17",
        "c4: CENTER ATOMS=79,83",
         "phi: TORSION ATOMS=c1,c2,c3,c4",
         "metad: METAD ARG=phi SIGMA=1.10 HEIGHT=15.0 BIASFACTOR=5 TEMP=300.0 PACE=1", #GRID_MIN=-pi GRID_MAX=pi GRID_BIN=1500
         # "ARG=d SIGMA=0.20,0.20 HEIGHT=1.20 BIASFACTOR=5 TEMP=300.0 PACE=500",
         # "GRID_MIN=0,0 GRID_MAX=1.0,1.0 GRID_BIN=150,150",
         "PRINT ARG=phi STRIDE=1 FILE=../results/test/plumed/COLVAR",
         # "CALC_RCT ",
         # "RCT_USTRIDE=10",
         # "...",
         "FLUSH STRIDE=1000"]

# setup = f"""
# d: DISTANCE ATOMS=1,2 
# metad: METAD ...
#    ARG=d SIGMA=0.20,0.20 HEIGHT=1.20 BIASFACTOR=5 TEMP=300.0 PACE=500 
#    GRID_MIN=0,0 GRID_MAX=1.0,1.0 GRID_BIN=150,150 
#    CALC_RCT 
#    RCT_USTRIDE=10 
# ...
# PRINT ARG=d STRIDE=100 FILE=COLVAR
# """
# print(setup)

from ase.build import molecule

atoms = read('../data/structures/new_systems/ktu_002.cif')
# atoms = molecule('CH3CH2NH2')
# atoms = read('../structures/Ar_isomer.xyz')
# atoms = read('../structures/KTU-183_2_auto.cif')
# atoms=read("../structures/HIK-143 293K-activated.cif")
# atoms=read("../structures/KTU-183_2_auto_dimer.xyz")
# cons = [FixedPlane(i, [0, 0, 1]) for i in range(7)]
# atoms.set_constraint(cons)
# atoms.set_masses([1, 1, 1, 1, 1, 1, 1])

# calc_base = LennardJones(rc=2.5, r0=3.)


fix_atoms = FixAtoms(indices=[atom.index for atom in atoms if atom.symbol=='N' or atom.symbol=='Si'])
# # ch_bonds = Analysis(atoms).get_bonds("C", "H")[0]
# # fix_bond_lengths = FixBondLengths(ch_bonds)
# # atoms.set_constraint([fix_atoms, fix_bond_lengths])
atoms.set_constraint(fix_atoms)



calc_base = Dftb(atoms=atoms,
            label='crystal',
            # Hamiltonian_ = "xTB",
            # Hamiltonian_Method = "GFN1-xTB",
            # Hamiltonian_MaxAngularMomentum_='',
            # Hamiltonian_MaxAngularMomentum_O='p',
            # Hamiltonian_MaxAngularMomentum_H='s',
            # Hamiltonian_MaxAngularMomentum_N='s',
            # Hamiltonian_MaxAngularMomentum_C='s',
            # Hamiltonian_MaxAngularMomentum_Si='s',
            kpts=(1,1,1),
            # Hamiltonian_SCC='Yes',
            # Verbosity=0,
            # Hamiltonian_OrbitalResolvedSCC = 'Yes',
            # Hamiltonian_SCCTolerance=1e-15,
            # kpts=None
            # Driver_='ConjugateGradient',
            # Driver_MaxForceComponent=1e-3,
            # Driver_MaxSteps=200,
            # Driver_LatticeOpt = 'Yes',
            # Driver_AppendGeometries = 'Yes'
            )

atoms.calc = Plumed(calc=calc_base,
                    input=setup,
                    timestep=timestep,
                    atoms=atoms,
                    kT=0.1,
                    log='../results/test/plumed/plumed_log.log')

from ase.md.verlet import VelocityVerlet
from ase.md.langevin import Langevin

# atoms.calc = calc_base

# calc=LennardJones(rc=2.5, r0=3.)
# atoms.calc = calc



dyn = Langevin(atoms, timestep, temperature_K=0.1/units.kB, friction=0.1,
               fixcm=True, trajectory='../results/test/plumed/MTD_output.xyz')
# We want to run MD with constant energy using the VelocityVerlet algorithm.
# dyn = VelocityVerlet(atoms, timestep, trajectory='../results/test/plumed/UnbiasMD.xyz')  # 5 fs time step.
# https://wiki.fysik.dtu.dk/ase/ase/md.html

dyn.run(500)


The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


+++ Loading the PLUMED kernel runtime +++
+++ PLUMED_KERNEL="/home/dlb/anaconda3/envs/dftb_plumed/lib/libplumedKernel.so" +++


True

In [21]:
from ase.visualize import view
view(atoms)



<Popen: returncode: None args: ['/home/dlb/anaconda3/envs/dftb_plumed/bin/py...>

In [61]:
print(atoms[6])
print(atoms[8])
print(atoms.get_cell())

Atom('C', [-0.3987443146369117, 6.614953598920975, 10.156099017572219], momentum=[0.63610629127762, -0.5983187487919405, 0.9573086067476068], index=6)
Atom('N', [-0.3945240324543453, 5.570663088011776, 11.064841535674525], momentum=[0.0, 0.0, 0.0], index=8)
Cell([[6.876, 0.0, 0.0], [-2.14253011477129, 19.188757872965567, 0.0], [-2.0842458005893625, -8.862442591006797, 19.133393629041198]])


In [60]:
from ase.io import read, write
from ase.visualize import view

traj = read('../results/test/plumed/MTD_output.xyz', index=":")
# traj = read('/home/dlb/Downloads/UnbiasMD.xyz', index=":")
# write("test/plumed/biased_MTD.xyz", traj, format="extxyz")
# traj_biased = read('test/plumed/biased_MTD.xyz', index=":")
# traj_unbiased = read('test/plumed/.xyz', index=":")

view(traj)

<Popen: returncode: None args: ['/home/dlb/anaconda3/envs/dftb_plumed/bin/py...>

Traceback (most recent call last):
  File "/home/dlb/anaconda3/envs/dftb_plumed/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/dlb/anaconda3/envs/dftb_plumed/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/dlb/anaconda3/envs/dftb_plumed/lib/python3.10/site-packages/ase/gui/pipe.py", line 32, in <module>
    main()
  File "/home/dlb/anaconda3/envs/dftb_plumed/lib/python3.10/site-packages/ase/gui/pipe.py", line 28, in main
    plt.show()
  File "/home/dlb/anaconda3/envs/dftb_plumed/lib/python3.10/site-packages/matplotlib/pyplot.py", line 421, in show
    return _get_backend_mod().show(*args, **kwargs)
  File "/home/dlb/anaconda3/envs/dftb_plumed/lib/python3.10/site-packages/matplotlib_inline/backend_inline.py", line 90, in show
    display(
  File "/home/dlb/anaconda3/envs/dftb_plumed/lib/python3.10/site-packages/IPython/core/display_functions.py", line 265, in display
    p

In [33]:
traj[1].get_forces()

array([[-0.44644934, -0.18941263,  0.21633226],
       [ 0.40692937, -0.30407194,  0.24245202],
       [ 0.10791414,  0.41096982,  0.25219211],
       ...,
       [-3.28981211,  2.13228102, -2.45460851],
       [-0.21308291, -3.87824713, -2.44825911],
       [ 3.3619705 ,  1.71517904, -2.36869344]])

In [34]:
# del test_at

test_at = traj[1].copy()


test_at.calc = calc_base

# print(test_at.get_potential_energy())
print(test_at.get_forces())

[[-0.44644934 -0.18941263  0.21633226]
 [ 0.40692937 -0.30407194  0.24245202]
 [ 0.10791414  0.41096982  0.25219211]
 ...
 [-3.28981211  2.13228102 -2.45460851]
 [-0.21308291 -3.87824713 -2.44825911]
 [ 3.3619705   1.71517904 -2.36869344]]


In [ ]:
# # Get unbiased forces:

# traj_unbiased = read('test/plumed/biased_MTD.xyz', index=":")

# for im in traj_unbiased:
#         im.calc = calc_base
#         # im.get_forces()
#         print(im.get_forces())

# write("test/plumed/unbiased_MTD.xyz", traj_unbiased, format="extxyz")

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

traj_biased = read('test/plumed/biased_MTD.xyz', index=":")
traj_unbiased = read('test/plumed/unbiased_MTD.xyz', index=":")

f_diff = np.zeros((len(traj_biased), len(traj_biased[0]), 3))
e_diff = np.zeros((len(traj_biased)))

for i in range(len(traj_biased)):
        f_diff[i] = traj_biased[i].get_forces() - traj_unbiased[i].get_forces()
        e_diff[i] = traj_biased[i].get_potential_energy() - traj_unbiased[i].get_potential_energy()


        # print(f_diff)

force_diffs = np.absolute(f_diff).sum(axis=(1,2))
plt.plot(force_diffs)
plt.show()


energy_diffs = np.absolute(e_diff)
plt.plot(energy_diffs)
plt.show()
# f_diff[0].absolutize().sum()

## Extract connected components

In [ ]:
from ase.build import connected_indices, connected_atoms, separate, split_bond
# view(connected_atoms(atoms, 0))
# separate(atoms)
view(split_bond(atoms, 0, 1))

## Make supercell

In [ ]:
from ase.build import make_supercell

new_cryst = make_supercell(crystal,[[2,0,0], [0,2,0], [0,0,2]])
print(new_cryst)
view(new_cryst)

## Lammps


In [67]:
#  export ASE_LAMMPSRUN_COMMAND=/path/to/lmp_binary
# pkill -9 -f lmp_serial

import os

os.environ["ASE_LAMMPSRUN_COMMAND"] = "lmp_serial"

In [84]:
%%time

from ase import Atoms, Atom
# from ase.calculators.lammpsrun import LAMMPS

# https://gitlab.com/ase/ase/-/issues/1096
from runner.lammpsrun import LAMMPS

from ase.io import read


atoms = read('../data/structures/new_systems/ktu_002.cif')

# a = [6.5, 6.5, 7.7]
# d = 2.3608
# NaCl = Atoms([Atom('Na', [0, 0, 0]),
#               Atom('Cl', [0, 0, d])],
#              cell=a, pbc=True)

calc = LAMMPS()
atoms.calc = calc
# NaCl.calc = calc

print(atoms.get_forces())

[[ 2.75694705e-01  1.59542825e-01  2.00582215e-01]
 [-2.75694705e-01 -1.59542825e-01 -2.00582215e-01]
 [ 1.93653935e-01 -1.09878166e-02 -2.61897700e-01]
 [-1.93653935e-01  1.09878166e-02  2.61897700e-01]
 [-3.30727297e-01 -1.73616057e-02 -9.69807151e-02]
 [ 3.30727297e-01  1.73616057e-02  9.69807151e-02]
 [ 6.81267887e-02 -5.06569241e-02 -7.07113394e-02]
 [-6.81267887e-02  5.06569241e-02  7.07113394e-02]
 [-3.86898726e-03 -4.19596290e-01 -1.69974527e+00]
 [ 3.86898726e-03  4.19596290e-01  1.69974527e+00]
 [-4.62388514e-02  2.89769225e-02  4.33143847e-02]
 [ 4.62388514e-02 -2.89769225e-02 -4.33143847e-02]
 [-1.96201017e-01  1.66587781e+00  4.92917890e-01]
 [ 1.96201017e-01 -1.66587781e+00 -4.92917890e-01]
 [ 4.37135258e-02  2.40124134e-02  1.18696384e-03]
 [-4.37135258e-02 -2.40124134e-02 -1.18696384e-03]
 [ 2.07246097e-01 -1.25503877e+00  1.20582993e+00]
 [-2.07246097e-01  1.25503877e+00 -1.20582993e+00]
 [-3.65243939e-01 -1.67007890e+00 -2.18058444e-01]
 [ 3.65243939e-01  1.67007890e+

/home/dlb/anaconda3/envs/dftb_plumed/lib/python3.10/site-packages/ase/io/cif.py:401: UserWarning: crystal system 'triclinic' is not interpreted for space group Spacegroup(2, setting=1). This may result in wrong setting!
  warnings.warn(


In [107]:
from ase.md.verlet import VelocityVerlet
from ase.md.langevin import Langevin

# atoms.calc = calc_base

# calc=LennardJones(rc=2.5, r0=3.)
# atoms.calc = calc
atoms = read('../data/structures/new_systems/ktu_002.cif')
calc = LAMMPS()
atoms.calc = calc

ch_bonds = Analysis(atoms).get_bonds("C", "H")[0]
fix_bond_lengths = FixBondLengths(ch_bonds)
atoms.set_constraint(fix_bond_lengths)


timestep = 0.05

dyn = Langevin(atoms, timestep, temperature_K=0.1/units.kB, friction=0.1,
               fixcm=True, trajectory='../results/test/plumed/lammps_output.xyz')
# We want to run MD with constant energy using the VelocityVerlet algorithm.
# dyn = VelocityVerlet(atoms, timestep, trajectory='../results/test/plumed/UnbiasMD.xyz')  # 5 fs time step.
# https://wiki.fysik.dtu.dk/ase/ase/md.html

dyn.run(100)

/home/dlb/anaconda3/envs/dftb_plumed/lib/python3.10/site-packages/ase/io/cif.py:401: UserWarning: crystal system 'triclinic' is not interpreted for space group Spacegroup(2, setting=1). This may result in wrong setting!
  warnings.warn(


KeyboardInterrupt: 

In [105]:
from ase.io import read, write
from ase.visualize import view

traj = read('../results/test/plumed/lammps_output.xyz', index=":")
# traj = read('/home/dlb/Downloads/UnbiasMD.xyz', index=":")
# write("test/plumed/biased_MTD.xyz", traj, format="extxyz")
# traj_biased = read('test/plumed/biased_MTD.xyz', index=":")
# traj_unbiased = read('test/plumed/.xyz', index=":")

view(traj)

<Popen: returncode: None args: ['/home/dlb/anaconda3/envs/dftb_plumed/bin/py...>

Traceback (most recent call last):
  File "/home/dlb/anaconda3/envs/dftb_plumed/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/dlb/anaconda3/envs/dftb_plumed/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/dlb/anaconda3/envs/dftb_plumed/lib/python3.10/site-packages/ase/gui/pipe.py", line 32, in <module>
    main()
  File "/home/dlb/anaconda3/envs/dftb_plumed/lib/python3.10/site-packages/ase/gui/pipe.py", line 28, in main
    plt.show()
  File "/home/dlb/anaconda3/envs/dftb_plumed/lib/python3.10/site-packages/matplotlib/pyplot.py", line 421, in show
    return _get_backend_mod().show(*args, **kwargs)
  File "/home/dlb/anaconda3/envs/dftb_plumed/lib/python3.10/site-packages/matplotlib_inline/backend_inline.py", line 90, in show
    display(
  File "/home/dlb/anaconda3/envs/dftb_plumed/lib/python3.10/site-packages/IPython/core/display_functions.py", line 265, in display
    p